import sys
import os

HEADER = [
    "author", "title", "author_born", "author_died", "origin", "genre",
    "subject_era", "exam_status", "memorize", "grade", "source", "doc_year",
    "retrieved", "note"
]

SRC_NIKOLENKO = "https://osvita.ua/doc/files/news/830/83093/Zarubizhna_literatura_5-9kl_Nikolenko_ta_.pdf"
SRC_VOLOSHCHUK = "https://osvita.ua/doc/files/news/901/90119/Zarubizhna_literatura_7-9_kl_Voloshchuk_.pdf"
SRC_YATSENKO = "https://osvita.ua/doc/files/news/896/89669/Ukrayinska_literatura_7-9-kl_Yatsenko_ta.pdf"
SRC_UKRMOVA = "https://osvita.ua/doc/files/news/9/946/Ukrmova.pdf"

rows = [
    # --- UKRAINIAN LITERATURE (DOMESTIC CANON) ---
    {
        "author": "Народна творчість (Folk Literature)",
        "title": "Українські народні балади («Ой летіла стріла», «Ой на горі вогонь горить») (Ukrainian Folk Ballads: \"Oh a Shot Flew\", \"Oh Fire Burns on the Mountain\")",
        "author_born": "traditional",
        "author_died": "traditional",
        "origin": "domestic",
        "genre": "poem-cycle",
        "subject_era": "Cossack-era",
        "exam_status": "mandatory",
        "memorize": "no",
        "grade": "9",
        "source": SRC_YATSENKO,
        "doc_year": "2023",
        "retrieved": "2026-08-10",
        "note": "Prescribed in Ukrainian Literature Grade 9"
    },
    {
        "author": "Невідомий автор (Unknown Author)",
        "title": "«Слово про похід Ігорів» (The Tale of Igor's Campaign)",
        "author_born": "12th c.",
        "author_died": "12th c.",
        "origin": "domestic",
        "genre": "epic",
        "subject_era": "Kyivan-Rus",
        "exam_status": "mandatory",
        "memorize": "excerpt",
        "grade": "9",
        "source": SRC_YATSENKO,
        "doc_year": "2023",
        "retrieved": "2026-08-10",
        "note": "Recitation of 'Yaroslavna's Lament' excerpt mandated in Grade 9 expected outcomes"
    },
    {
        "author": "Літописний переказ (Chronicle Narrative)",
        "title": "«Повість минулих літ» (уривки про заснування Києва, про помсту княгині Ольги) (Primary Chronicle: Excerpts on the Founding of Kyiv and Princess Olga's Revenge)",
        "author_born": "12th c.",
        "author_died": "12th c.",
        "origin": "domestic",
        "genre": "essay",
        "subject_era": "Kyivan-Rus",
        "exam_status": "mandatory",
        "memorize": "no",
        "grade": "9",
        "source": SRC_UKRMOVA,
        "doc_year": "2024",
        "retrieved": "2026-08-10",
        "note": "Prescribed old Ukrainian literature text"
    },
    {
        "author": "Григорій Сковорода (Hryhoriy Skovoroda)",
        "title": "«De libertate», «Всякому місту — звичай і права…», «Бджола та Шершень» (De Libertate; Every City Has Its Custom and Laws; The Bee and the Hornet)",
        "author_born": "1722",
        "author_died": "1794",
        "origin": "domestic",
        "genre": "poem-cycle",
        "subject_era": "Enlightenment",
        "exam_status": "mandatory",
        "memorize": "yes",
        "grade": "9",
        "source": SRC_YATSENKO,
        "doc_year": "2023",
        "retrieved": "2026-08-10",
        "note": "Recitation of De libertate mandated in Grade 9 expected outcomes"
    },
    {
        "author": "Іван Котляревський (Ivan Kotlyarevsky)",
        "title": "«Енеїда», «Наталка Полтавка» (Eneida; Natalka Poltavka)",
        "author_born": "1769",
        "author_died": "1838",
        "origin": "domestic",
        "genre": "epic",
        "subject_era": "Cossack-era",
        "exam_status": "mandatory",
        "memorize": "no",
        "grade": "9",
        "source": SRC_YATSENKO,
        "doc_year": "2023",
        "retrieved": "2026-08-10",
        "note": "Foundational modern Ukrainian literary works"
    },
    {
        "author": "Тарас Шевченко (Taras Shevchenko)",
        "title": "«Катерина», «Кавказ», «Сон» («У всякого своя доля…»), «І мертвим, і живим, і ненарожденним…», «Заповіт» (Kateryna; The Caucasus; The Dream; To the Dead, the Living, and the Unborn; Testament)",
        "author_born": "1814",
        "author_died": "1861",
        "origin": "domestic",
        "genre": "poem-cycle",
        "subject_era": "serfdom",
        "exam_status": "mandatory",
        "memorize": "yes",
        "grade": "9",
        "source": SRC_YATSENKO,
        "doc_year": "2023",
        "retrieved": "2026-08-10",
        "note": "Mandatory recitation of Zapovit mandated in Grade 9 expected outcomes"
    },
    {
        "author": "Пантелеймон Куліш (Panteleimon Kulish)",
        "title": "«Чорна рада» (The Black Council)",
        "author_born": "1819",
        "author_died": "1897",
        "origin": "domestic",
        "genre": "novel",
        "subject_era": "Cossack-era",
        "exam_status": "mandatory",
        "memorize": "no",
        "grade": "9",
        "source": SRC_YATSENKO,
        "doc_year": "2023",
        "retrieved": "2026-08-10",
        "note": "First Ukrainian historical novel"
    },
    {
        "author": "Марко Вовчок (Marko Vovchok)",
        "title": "«Інститутка» (The Institution Girl)",
        "author_born": "1833",
        "author_died": "1907",
        "origin": "domestic",
        "genre": "novella",
        "subject_era": "serfdom",
        "exam_status": "mandatory",
        "memorize": "no",
        "grade": "9",
        "source": SRC_YATSENKO,
        "doc_year": "2023",
        "retrieved": "2026-08-10",
        "note": "Anti-serfdom realistic story"
    },
    {
        "author": "Микола Гоголь (Nikolai Gogol)",
        "title": "«Тарас Бульба» (Taras Bulba)",
        "author_born": "1809",
        "author_died": "1852",
        "origin": "domestic",
        "genre": "novella",
        "subject_era": "Cossack-era",
        "exam_status": "mandatory",
        "memorize": "no",
        "grade": "9",
        "source": SRC_YATSENKO,
        "doc_year": "2023",
        "retrieved": "2026-08-10",
        "note": "Retained in Ukrainian Literature due to Ukrainian history and author origin"
    },
    {
        "author": "Іван Франко (Ivan Franko)",
        "title": "«Захар Беркут», «Чого являєшся мені у сні?..», «Мойсей» (Zakhar Berkut; Why Do You Appear to Me in My Dreams?; Moses)",
        "author_born": "1856",
        "author_died": "1916",
        "origin": "domestic",
        "genre": "poem-cycle",
        "subject_era": "13th-c-mongol-invasion?",
        "exam_status": "mandatory",
        "memorize": "yes",
        "grade": "9",
        "source": SRC_YATSENKO,
        "doc_year": "2023",
        "retrieved": "2026-08-10",
        "note": "Recitation of Chogo yavlyayeshsya meni u sni mandated in Grade 9 expected outcomes"
    },
    {
        "author": "Михайло Коцюбинський (Mykhailo Kotsiubynsky)",
        "title": "«Тіні забутих предків», «Intermezzo» (Shadows of Forgotten Ancestors; Intermezzo)",
        "author_born": "1864",
        "author_died": "1913",
        "origin": "domestic",
        "genre": "novella",
        "subject_era": "none/romance?",
        "exam_status": "mandatory",
        "memorize": "no",
        "grade": "9",
        "source": SRC_YATSENKO,
        "doc_year": "2023",
        "retrieved": "2026-08-10",
        "note": "Hutsul life and modernist impressionism"
    },
    {
        "author": "Ольга Кобилянська (Olha Kobylianska)",
        "title": "«Людина», «Valse mélancolique» (A Human; Valse Mélancolique)",
        "author_born": "1863",
        "author_died": "1942",
        "origin": "domestic",
        "genre": "novella",
        "subject_era": "none/romance?",
        "exam_status": "mandatory",
        "memorize": "no",
        "grade": "9",
        "source": SRC_YATSENKO,
        "doc_year": "2023",
        "retrieved": "2026-08-10",
        "note": "Feminist literature and Bukovinian modernist prose"
    },
    {
        "author": "Леся Українка (Lesya Ukrainka)",
        "title": "«Давня казка», «Contra spem spero!», «Лісова пісня» (An Old Tale; Contra Spem Spero!; The Forest Song)",
        "author_born": "1871",
        "author_died": "1913",
        "origin": "domestic",
        "genre": "play",
        "subject_era": "none/romance?",
        "exam_status": "mandatory",
        "memorize": "yes",
        "grade": "9",
        "source": SRC_YATSENKO,
        "doc_year": "2023",
        "retrieved": "2026-08-10",
        "note": "Recitation of Contra spem spero mandated in Grade 9 expected outcomes"
    },
    {
        "author": "Микола Вороний (Mykola Voronyi)",
        "title": "«Блакитна Панна» (The Blue Lady)",
        "author_born": "1871",
        "author_died": "1938",
        "origin": "domestic",
        "genre": "poem",
        "subject_era": "none/romance?",
        "exam_status": "mandatory",
        "memorize": "no",
        "grade": "9",
        "source": SRC_YATSENKO,
        "doc_year": "2023",
        "retrieved": "2026-08-10",
        "note": "Modernist poetry"
    },
    {
        "author": "Іван Багряний (Ivan Bahrianyi)",
        "title": "«Тигролови» (The Tiger Catchers)",
        "author_born": "1906",
        "author_died": "1963",
        "origin": "domestic",
        "genre": "novel",
        "subject_era": "totalitarianism",
        "exam_status": "mandatory",
        "memorize": "no",
        "grade": "9",
        "source": SRC_YATSENKO,
        "doc_year": "2023",
        "retrieved": "2026-08-10",
        "note": "Stalinist repressions and Ukrainian GULAG escape novel"
    },
    {
        "author": "Василь Симоненко (Vasyl Symonenko)",
        "title": "«Ти знаєш, що ти — людина?», «Задивляюсь у твої зіниці…», «Лебеді материнства» (Do You Know That You Are Human?; I Look Into Your Pupils; Swans of Motherhood)",
        "author_born": "1935",
        "author_died": "1963",
        "origin": "domestic",
        "genre": "poem-cycle",
        "subject_era": "totalitarianism",
        "exam_status": "mandatory",
        "memorize": "yes",
        "grade": "9",
        "source": SRC_YATSENKO,
        "doc_year": "2023",
        "retrieved": "2026-08-10",
        "note": "Recitation of Sixtiers poetry mandated in Grade 9 expected outcomes"
    },
    {
        "author": "Василь Стус (Vasyl Stus)",
        "title": "«Господи, гніву пречистого…» (Lord, Pure Wrath...)",
        "author_born": "1938",
        "author_died": "1985",
        "origin": "domestic",
        "genre": "poem",
        "subject_era": "totalitarianism",
        "exam_status": "mandatory",
        "memorize": "yes",
        "grade": "9",
        "source": SRC_YATSENKO,
        "doc_year": "2023",
        "retrieved": "2026-08-10",
        "note": "Recitation of Stus's poem mandated in Grade 9 expected outcomes"
    },
    {
        "author": "Євген Маланюк (Yevhen Malanyuk)",
        "title": "«Уривок з поеми» (Excerpt from a Poem)",
        "author_born": "1897",
        "author_died": "1968",
        "origin": "domestic",
        "genre": "poem",
        "subject_era": "1917-revolution",
        "exam_status": "mandatory",
        "memorize": "no",
        "grade": "9",
        "source": SRC_YATSENKO,
        "doc_year": "2023",
        "retrieved": "2026-08-10",
        "note": "Prague School diaspora poetry"
    },
    {
        "author": "Ервін Умеров (Ervin Umerov)",
        "title": "«Чорні ешелони» (Black Echelons)",
        "author_born": "1938",
        "author_died": "2007",
        "origin": "domestic",
        "genre": "novella",
        "subject_era": "WWII-occupation",
        "exam_status": "mandatory",
        "memorize": "no",
        "grade": "9",
        "source": SRC_YATSENKO,
        "doc_year": "2023",
        "retrieved": "2026-08-10",
        "note": "Crimean Tatar 1944 deportation novel in Ukrainian literature syllabus"
    },
    {
        "author": "Сучасна воєнна поезія (Modern War Poetry)",
        "title": "Поезії з розділу «Поезія Вільних» (Борис Гуменюк, Олекса Бик) (Poetry of the Free: Borys Humenyuk, Oleksa Byk)",
        "author_born": "living",
        "author_died": "living",
        "origin": "domestic",
        "genre": "poem-cycle",
        "subject_era": "post-2022-invasion",
        "exam_status": "mandatory",
        "memorize": "no",
        "grade": "9",
        "source": SRC_YATSENKO,
        "doc_year": "2023",
        "retrieved": "2026-08-10",
        "note": "Russo-Ukrainian war contemporary poetry unit"
    },

    # --- FOREIGN LITERATURE (TRANSLATED CANON) ---
    {
        "author": "Джонатан Свіфт (Jonathan Swift)",
        "title": "«Мандри Лемюеля Гуллівера» (частина 1) (Gulliver's Travels, Part 1: A Voyage to Lilliput)",
        "author_born": "1667",
        "author_died": "1745",
        "origin": "translated:English (doc-marked)",
        "genre": "novel",
        "subject_era": "Enlightenment",
        "exam_status": "mandatory",
        "memorize": "no",
        "grade": "9",
        "source": SRC_NIKOLENKO,
        "doc_year": "2022",
        "retrieved": "2026-08-10",
        "note": "Enlightenment satire"
    },
    {
        "author": "Йоганн Вольфганг фон Ґете (Johann Wolfgang von Goethe)",
        "title": "«Травнева пісня», «Прометей», «Вільшаний цар» (May Song; Prometheus; Erlkönig)",
        "author_born": "1749",
        "author_died": "1832",
        "origin": "translated:German (doc-marked)",
        "genre": "poem-cycle",
        "subject_era": "Enlightenment",
        "exam_status": "mandatory",
        "memorize": "no",
        "grade": "9",
        "source": SRC_NIKOLENKO,
        "doc_year": "2022",
        "retrieved": "2026-08-10",
        "note": "Sturm und Drang and Weimar Classicism"
    },
    {
        "author": "Фрідріх Шиллер (Friedrich Schiller)",
        "title": "«До радості» (An die Freude)",
        "author_born": "1759",
        "author_died": "1805",
        "origin": "translated:German (doc-marked)",
        "genre": "poem",
        "subject_era": "Enlightenment",
        "exam_status": "mandatory",
        "memorize": "no",
        "grade": "9",
        "source": SRC_NIKOLENKO,
        "doc_year": "2022",
        "retrieved": "2026-08-10",
        "note": "Ode to Joy"
    },
    {
        "author": "Генріх Гейне (Heinrich Heine)",
        "title": "«Книга пісень» («На півночі кедр одинокий…», «Не знаю, що стало зо мною…», «Коли розлучаються двоє…») (Book of Songs: A pine-tree stands alone in the north; I do not know what it means; When two people part)",
        "author_born": "1797",
        "author_died": "1856",
        "origin": "translated:German (doc-marked)",
        "genre": "poem-cycle",
        "subject_era": "none/romance?",
        "exam_status": "mandatory",
        "memorize": "yes",
        "grade": "9",
        "source": SRC_VOLOSHCHUK,
        "doc_year": "2023",
        "retrieved": "2026-08-10",
        "note": "Recitation mandated in Voloshchuk Grade 9 memorization list"
    },
    {
        "author": "Джордж Ноел Гордон Байрон (George Gordon Byron)",
        "title": "«Хотів би жити знов у горах…», «Мій дух як ніч…», «Паломництво Чайльд Гарольда», «Мазепа» (I would I were a careless child; My soul is dark; Childe Harold's Pilgrimage; Mazeppa)",
        "author_born": "1788",
        "author_died": "1824",
        "origin": "translated:English (doc-marked)",
        "genre": "poem-cycle",
        "subject_era": "Cossack-era",
        "exam_status": "mandatory",
        "memorize": "no",
        "grade": "9",
        "source": SRC_NIKOLENKO,
        "doc_year": "2022",
        "retrieved": "2026-08-10",
        "note": "Byronic hero and Ukrainian theme in Mazeppa"
    },
    {
        "author": "Данте Аліг'єрі (Dante Alighieri)",
        "title": "Сонет «В своїх очах вона несе Кохання…» (Sonnet: In her eyes she carries love)",
        "author_born": "1265",
        "author_died": "1321",
        "origin": "translated:Italian (doc-marked)",
        "genre": "poem",
        "subject_era": "antiquity?",
        "exam_status": "mandatory",
        "memorize": "yes",
        "grade": "9",
        "source": SRC_VOLOSHCHUK,
        "doc_year": "2023",
        "retrieved": "2026-08-10",
        "note": "Recitation mandated in Voloshchuk Grade 9 memorization list"
    },
    {
        "author": "Франческо Петрарка (Francesco Petrarca)",
        "title": "Сонет 61 або 132 (за вибором) (Sonnet 61 or 132 by choice)",
        "author_born": "1304",
        "author_died": "1374",
        "origin": "translated:Italian (doc-marked)",
        "genre": "poem",
        "subject_era": "antiquity?",
        "exam_status": "choice-list",
        "memorize": "yes",
        "grade": "9",
        "source": SRC_VOLOSHCHUK,
        "doc_year": "2023",
        "retrieved": "2026-08-10",
        "note": "Recitation mandated in Voloshchuk Grade 9 memorization list"
    },
    {
        "author": "Вільям Шекспір (William Shakespeare)",
        "title": "Сонет 116 або 130 (за вибором) (Sonnet 116 or 130 by choice)",
        "author_born": "1564",
        "author_died": "1616",
        "origin": "translated:English (doc-marked)",
        "genre": "poem",
        "subject_era": "none/romance?",
        "exam_status": "choice-list",
        "memorize": "yes",
        "grade": "9",
        "source": SRC_VOLOSHCHUK,
        "doc_year": "2023",
        "retrieved": "2026-08-10",
        "note": "Recitation mandated in Voloshchuk Grade 9 memorization list"
    },
    {
        "author": "Міхай Емінеску (Mihai Eminescu)",
        "title": "«Буковині» (To Bukovina)",
        "author_born": "1850",
        "author_died": "1889",
        "origin": "translated:Romanian (doc-marked)",
        "genre": "poem",
        "subject_era": "none/romance?",
        "exam_status": "mandatory",
        "memorize": "yes",
        "grade": "9",
        "source": SRC_VOLOSHCHUK,
        "doc_year": "2023",
        "retrieved": "2026-08-10",
        "note": "Recitation mandated in Voloshchuk Grade 9 memorization list"
    },
    {
        "author": "Оноре де Бальзак (Honoré de Balzac)",
        "title": "«Гобсек» (Gobseck)",
        "author_born": "1799",
        "author_died": "1850",
        "origin": "translated:French (doc-marked)",
        "genre": "novella",
        "subject_era": "none/romance?",
        "exam_status": "mandatory",
        "memorize": "no",
        "grade": "9",
        "source": SRC_NIKOLENKO,
        "doc_year": "2022",
        "retrieved": "2026-08-10",
        "note": "Realism and money theme"
    },
    {
        "author": "Микола Васильович Гоголь (Nikolai Gogol)",
        "title": "«Ревізор» АБО «Шинель» (за вибором) (The Government Inspector OR The Overcoat by choice)",
        "author_born": "1809",
        "author_died": "1852",
        "origin": "translated:Russian (doc-marked)",
        "genre": "play",
        "subject_era": "serfdom",
        "exam_status": "choice-list",
        "memorize": "no",
        "grade": "9",
        "source": SRC_NIKOLENKO,
        "doc_year": "2022",
        "retrieved": "2026-08-10",
        "note": "Retained Russian-language work due to author's Ukrainian origin"
    },
    {
        "author": "Гарпер Лі (Harper Lee)",
        "title": "«Убити пересмішника» (To Kill a Mockingbird)",
        "author_born": "1926",
        "author_died": "2016",
        "origin": "translated:English (doc-marked)",
        "genre": "novel",
        "subject_era": "post-WWII?",
        "exam_status": "mandatory",
        "memorize": "no",
        "grade": "9",
        "source": SRC_NIKOLENKO,
        "doc_year": "2022",
        "retrieved": "2026-08-10",
        "note": "US Southern racism and justice novel"
    },
    {
        "author": "Барбара Космовська (Barbara Kosmowska)",
        "title": "«Позолочена рибка» (Goldfish)",
        "author_born": "1958",
        "author_died": "living",
        "origin": "translated:Polish (doc-marked)",
        "genre": "novel",
        "subject_era": "none/romance?",
        "exam_status": "mandatory",
        "memorize": "no",
        "grade": "9",
        "source": SRC_NIKOLENKO,
        "doc_year": "2022",
        "retrieved": "2026-08-10",
        "note": "Contemporary YA prose"
    },
    {
        "author": "Генрік Ібсен (Henrik Ibsen)",
        "title": "«Ляльковий дім» (A Doll's House)",
        "author_born": "1828",
        "author_died": "1906",
        "origin": "translated:Norwegian (doc-marked)",
        "genre": "play",
        "subject_era": "none/romance?",
        "exam_status": "mandatory",
        "memorize": "no",
        "grade": "9",
        "source": SRC_NIKOLENKO,
        "doc_year": "2022",
        "retrieved": "2026-08-10",
        "note": "New Drama pioneer"
    },
    {
        "author": "Бернард Шоу (Bernard Shaw)",
        "title": "«Пігмаліон» (Pygmalion)",
        "author_born": "1856",
        "author_died": "1950",
        "origin": "translated:English (doc-marked)",
        "genre": "play",
        "subject_era": "none/romance?",
        "exam_status": "mandatory",
        "memorize": "no",
        "grade": "9",
        "source": SRC_NIKOLENKO,
        "doc_year": "2022",
        "retrieved": "2026-08-10",
        "note": "Intellectual drama and myth adaptation"
    },
    {
        "author": "Моріс Метерлінк (Maurice Maeterlinck)",
        "title": "«Синій птах» (The Blue Bird)",
        "author_born": "1862",
        "author_died": "1942",
        "origin": "translated:French (doc-marked)",
        "genre": "play",
        "subject_era": "none/romance?",
        "exam_status": "mandatory",
        "memorize": "no",
        "grade": "9",
        "source": SRC_NIKOLENKO,
        "doc_year": "2022",
        "retrieved": "2026-08-10",
        "note": "Symbolist drama-fairy tale"
    },
    {
        "author": "Шолом-Алейхем (Sholem Aleichem)",
        "title": "«Тев'є-молочар» (Tevye the Dairyman)",
        "author_born": "1859",
        "author_died": "1916",
        "origin": "translated:Yiddish (doc-marked)",
        "genre": "novel",
        "subject_era": "serfdom?",
        "exam_status": "choice-list",
        "memorize": "no",
        "grade": "9",
        "source": SRC_NIKOLENKO,
        "doc_year": "2022",
        "retrieved": "2026-08-10",
        "note": "Jewish-Ukrainian historical experience"
    },
    {
        "author": "Михайло Булгаков (Mikhail Bulgakov)",
        "title": "«Собаче серце» (Heart of a Dog)",
        "author_born": "1891",
        "author_died": "1940",
        "origin": "translated:Russian (doc-marked)",
        "genre": "novella",
        "subject_era": "1917-revolution",
        "exam_status": "choice-list",
        "memorize": "no",
        "grade": "9",
        "source": SRC_NIKOLENKO,
        "doc_year": "2022",
        "retrieved": "2026-08-10",
        "note": "Retained Russian-language work due to author's Kyivan birth and anti-totalitarian satire"
    },
    {
        "author": "Рей Бредбері (Ray Bradbury)",
        "title": "«451° за Фаренгейтом» (Fahrenheit 451)",
        "author_born": "1920",
        "author_died": "2012",
        "origin": "translated:English (doc-marked)",
        "genre": "novel",
        "subject_era": "totalitarianism",
        "exam_status": "choice-list",
        "memorize": "no",
        "grade": "9",
        "source": SRC_NIKOLENKO,
        "doc_year": "2022",
        "retrieved": "2026-08-10",
        "note": "Dystopian anti-totalitarian novel"
    },
    {
        "author": "Маркус Зузак (Markus Zusak)",
        "title": "«Крадійка книжок» (The Book Thief)",
        "author_born": "1975",
        "author_died": "living",
        "origin": "translated:English (doc-marked)",
        "genre": "novel",
        "subject_era": "WWII-occupation",
        "exam_status": "choice-list",
        "memorize": "no",
        "grade": "9",
        "source": SRC_NIKOLENKO,
        "doc_year": "2022",
        "retrieved": "2026-08-10",
        "note": "WWII Holocaust/Nazi Germany perspective"
    },
    {
        "author": "Джонатан Сафран Фоер (Jonathan Safran Foer)",
        "title": "«Страшенно голосно і неймовірно близько» (Extremely Loud & Incredibly Close)",
        "author_born": "1977",
        "author_died": "living",
        "origin": "translated:English (doc-marked)",
        "genre": "novel",
        "subject_era": "post-WWII?",
        "exam_status": "choice-list",
        "memorize": "no",
        "grade": "9",
        "source": SRC_NIKOLENKO,
        "doc_year": "2022",
        "retrieved": "2026-08-10",
        "note": "Post-9/11 tragedy novel"
    },

    # --- NIKOLENKO APPENDIX 2 (CHOICE LIST FOR GRADE 9 EXTENDED READING) ---
    {
        "author": "Айзек Азімов (Isaac Asimov)",
        "title": "«Я – робот» (I, Robot)",
        "author_born": "1920",
        "author_died": "1992",
        "origin": "translated:English (doc-marked)",
        "genre": "short-story",
        "subject_era": "none/romance?",
        "exam_status": "choice-list",
        "memorize": "no",
        "grade": "9",
        "source": SRC_NIKOLENKO,
        "doc_year": "2022",
        "retrieved": "2026-08-10",
        "note": "Science fiction choice list"
    },
    {
        "author": "Рюноске Акутаґава (Ryūnosuke Akutagawa)",
        "title": "«Ніс», «Свято хризантем» (1 за вибором) (The Nose; The Chrysanthemum Vow by choice)",
        "author_born": "1892",
        "author_died": "1927",
        "origin": "translated:Japanese (doc-marked)",
        "genre": "short-story",
        "subject_era": "none/romance?",
        "exam_status": "choice-list",
        "memorize": "no",
        "grade": "9",
        "source": SRC_NIKOLENKO,
        "doc_year": "2022",
        "retrieved": "2026-08-10",
        "note": "Japanese modernist short story choice"
    },
    {
        "author": "Шарлотта Бронте (Charlotte Brontë)",
        "title": "«Джейн Ейр» (Jane Eyre)",
        "author_born": "1816",
        "author_died": "1855",
        "origin": "translated:English (doc-marked)",
        "genre": "novel",
        "subject_era": "none/romance?",
        "exam_status": "choice-list",
        "memorize": "no",
        "grade": "9",
        "source": SRC_NIKOLENKO,
        "doc_year": "2022",
        "retrieved": "2026-08-10",
        "note": "Victorian romance choice list"
    },
    {
        "author": "Вільям Ґолдінґ (William Golding)",
        "title": "«Володар мух» (Lord of the Flies)",
        "author_born": "1911",
        "author_died": "1993",
        "origin": "translated:English (doc-marked)",
        "genre": "novel",
        "subject_era": "post-WWII?",
        "exam_status": "choice-list",
        "memorize": "no",
        "grade": "9",
        "source": SRC_NIKOLENKO,
        "doc_year": "2022",
        "retrieved": "2026-08-10",
        "note": "Post-WWII allegory choice list"
    },
    {
        "author": "Віктор Гюго (Victor Hugo)",
        "title": "«Собор Паризької Богоматері» (The Hunchback of Notre-Dame)",
        "author_born": "1802",
        "author_died": "1885",
        "origin": "translated:French (doc-marked)",
        "genre": "novel",
        "subject_era": "antiquity?",
        "exam_status": "choice-list",
        "memorize": "no",
        "grade": "9",
        "source": SRC_NIKOLENKO,
        "doc_year": "2022",
        "retrieved": "2026-08-10",
        "note": "French romantic novel choice list"
    },
    {
        "author": "Артур Кларк (Arthur C. Clarke)",
        "title": "«Кінець дитинства» (Childhood's End)",
        "author_born": "1917",
        "author_died": "2008",
        "origin": "translated:English (doc-marked)",
        "genre": "novel",
        "subject_era": "none/romance?",
        "exam_status": "choice-list",
        "memorize": "no",
        "grade": "9",
        "source": SRC_NIKOLENKO,
        "doc_year": "2022",
        "retrieved": "2026-08-10",
        "note": "Sci-fi choice list"
    },
    {
        "author": "Джозеф Конрад (Joseph Conrad)",
        "title": "«Серце темряви» (Heart of Darkness)",
        "author_born": "1857",
        "author_died": "1924",
        "origin": "translated:English (doc-marked)",
        "genre": "novella",
        "subject_era": "none/romance?",
        "exam_status": "choice-list",
        "memorize": "no",
        "grade": "9",
        "source": SRC_NIKOLENKO,
        "doc_year": "2022",
        "retrieved": "2026-08-10",
        "note": "Colonial critique choice list (Conrad born in Berdychiv, Ukraine)"
    },
    {
        "author": "Проспер Меріме (Prosper Mérimée)",
        "title": "«Кармен» (Carmen)",
        "author_born": "1803",
        "author_died": "1870",
        "origin": "translated:French (doc-marked)",
        "genre": "novella",
        "subject_era": "none/romance?",
        "exam_status": "choice-list",
        "memorize": "no",
        "grade": "9",
        "source": SRC_NIKOLENKO,
        "doc_year": "2022",
        "retrieved": "2026-08-10",
        "note": "French romantic novella choice list"
    },
    {
        "author": "Едґар Аллан По (Edgar Allan Poe)",
        "title": "«Ельдорадо» та ін. (Eldorado and Other Poems)",
        "author_born": "1809",
        "author_died": "1849",
        "origin": "translated:English (doc-marked)",
        "genre": "poem-cycle",
        "subject_era": "none/romance?",
        "exam_status": "choice-list",
        "memorize": "no",
        "grade": "9",
        "source": SRC_NIKOLENKO,
        "doc_year": "2022",
        "retrieved": "2026-08-10",
        "note": "American Romantic poetry choice list"
    },
    {
        "author": "Еріх Марія Ремарк (Erich Maria Remarque)",
        "title": "«Три товариші» (Three Comrades)",
        "author_born": "1898",
        "author_died": "1970",
        "origin": "translated:German (doc-marked)",
        "genre": "novel",
        "subject_era": "post-WWII?",
        "exam_status": "choice-list",
        "memorize": "no",
        "grade": "9",
        "source": SRC_NIKOLENKO,
        "doc_year": "2022",
        "retrieved": "2026-08-10",
        "note": "Interwar lost generation novel choice list"
    },
    {
        "author": "Джером Девід Селінджер (J. D. Salinger)",
        "title": "«Над прірвою у житі» (The Catcher in the Rye)",
        "author_born": "1919",
        "author_died": "2010",
        "origin": "translated:English (doc-marked)",
        "genre": "novel",
        "subject_era": "post-WWII?",
        "exam_status": "choice-list",
        "memorize": "no",
        "grade": "9",
        "source": SRC_NIKOLENKO,
        "doc_year": "2022",
        "retrieved": "2026-08-10",
        "note": "American post-war coming-of-age novel choice list"
    },
    {
        "author": "Генрик Сенкевич (Henryk Sienkiewicz)",
        "title": "«Камо грядеші?» (Quo Vadis)",
        "author_born": "1846",
        "author_died": "1916",
        "origin": "translated:Polish (doc-marked)",
        "genre": "novel",
        "subject_era": "antiquity?",
        "exam_status": "choice-list",
        "memorize": "no",
        "grade": "9",
        "source": SRC_NIKOLENKO,
        "doc_year": "2022",
        "retrieved": "2026-08-10",
        "note": "Ancient Rome historical novel choice list"
    },
    {
        "author": "Колсон Вайтхед (Colson Whitehead)",
        "title": "«Підземна залізниця» (The Underground Railroad)",
        "author_born": "1969",
        "author_died": "living",
        "origin": "translated:English (doc-marked)",
        "genre": "novel",
        "subject_era": "serfdom?",
        "exam_status": "choice-list",
        "memorize": "no",
        "grade": "9",
        "source": SRC_NIKOLENKO,
        "doc_year": "2022",
        "retrieved": "2026-08-10",
        "note": "Slavery historical novel choice list"
    },
    {
        "author": "Марк Геддон (Mark Haddon)",
        "title": "«Загадковий нічний інцидент із собакою» (The Curious Incident of the Dog in the Night-Time)",
        "author_born": "1962",
        "author_died": "living",
        "origin": "translated:English (doc-marked)",
        "genre": "novel",
        "subject_era": "none/romance?",
        "exam_status": "choice-list",
        "memorize": "no",
        "grade": "9",
        "source": SRC_NIKOLENKO,
        "doc_year": "2022",
        "retrieved": "2026-08-10",
        "note": "Modern British YA fiction choice list"
    },
    {
        "author": "Лоран Гунель (Laurent Gounelle)",
        "title": "«Бог завжди подорожує інкогніто» (God Always Travels Incognito)",
        "author_born": "1966",
        "author_died": "living",
        "origin": "translated:French (doc-marked)",
        "genre": "novel",
        "subject_era": "none/romance?",
        "exam_status": "choice-list",
        "memorize": "no",
        "grade": "9",
        "source": SRC_NIKOLENKO,
        "doc_year": "2022",
        "retrieved": "2026-08-10",
        "note": "Modern French fiction choice list"
    },
    {
        "author": "Майкл Морпурго (Michael Morpurgo)",
        "title": "«Бойовий кінь» (War Horse)",
        "author_born": "1943",
        "author_died": "living",
        "origin": "translated:English (doc-marked)",
        "genre": "novel",
        "subject_era": "WWII-occupation?",
        "exam_status": "choice-list",
        "memorize": "no",
        "grade": "9",
        "source": SRC_NIKOLENKO,
        "doc_year": "2022",
        "retrieved": "2026-08-10",
        "note": "WWI British novel choice list"
    },
    {
        "author": "Джоан Ролінґ (J. K. Rowling)",
        "title": "«Гаррі Поттер і орден Фенікса» (Harry Potter and the Order of the Phoenix)",
        "author_born": "1965",
        "author_died": "living",
        "origin": "translated:English (doc-marked)",
        "genre": "novel",
        "subject_era": "none/romance?",
        "exam_status": "choice-list",
        "memorize": "no",
        "grade": "9",
        "source": SRC_NIKOLENKO,
        "doc_year": "2022",
        "retrieved": "2026-08-10",
        "note": "Modern British fantasy choice list"
    },
    {
        "author": "Ерік-Емманюель Шмітт (Éric-Emmanuel Schmitt)",
        "title": "«Оскар і Рожева Пані» (Oscar and the Lady in Pink)",
        "author_born": "1960",
        "author_died": "living",
        "origin": "translated:French (doc-marked)",
        "genre": "novella",
        "subject_era": "none/romance?",
        "exam_status": "choice-list",
        "memorize": "no",
        "grade": "9",
        "source": SRC_NIKOLENKO,
        "doc_year": "2022",
        "retrieved": "2026-08-10",
        "note": "Contemporary French novella choice list"
    }
]

output_path = "/home/diablo/book10/corpus/ua-2024.tsv"
os.makedirs(os.path.dirname(output_path), exist_ok=True)

with open(output_path, "w", encoding="utf-8") as f:
    f.write("\t".join(HEADER) + "\n")
    for r in rows:
        row_str = "\t".join([str(r[h]) for h in HEADER])
        f.write(row_str + "\n")

print(f"Successfully generated {output_path} with {len(rows)} rows.")
