import csv
import os

headers = [
    'author', 'title', 'author_born', 'author_died', 'origin', 'genre',
    'subject_era', 'exam_status', 'memorize', 'grade', 'source', 'doc_year',
    'retrieved', 'note'
]

rows = [
    # --- FIRST FLIGHT (PROSE) ---
    {
        'author': 'Gregorio López y Fuentes',
        'title': 'A Letter to God',
        'author_born': '1895',
        'author_died': '1966',
        'origin': 'translated:spanish',
        'genre': 'short-story',
        'subject_era': '20th-c-mexican-peasantry/faith?',
        'exam_status': 'mandatory',
        'memorize': 'no',
        'grade': '10',
        'source': 'https://cbseacademic.nic.in/web_material/CurriculumMain25/Sec/English_LL_2024-25.pdf',
        'doc_year': '2024',
        'retrieved': '2026-08-10',
        'note': 'First Flight Prose Ch 1; Mexican story translated from Spanish (Una carta a Dios)'
    },
    {
        'author': 'Nelson Mandela',
        'title': 'Nelson Mandela: Long Walk to Freedom',
        'author_born': '1918',
        'author_died': '2013',
        'origin': 'translated:english',
        'genre': 'essay',
        'subject_era': 'apartheid-south-africa',
        'exam_status': 'mandatory',
        'memorize': 'no',
        'grade': '10',
        'source': 'https://cbseacademic.nic.in/web_material/CurriculumMain25/Sec/English_LL_2024-25.pdf',
        'doc_year': '2024',
        'retrieved': '2026-08-10',
        'note': 'First Flight Prose Ch 2; excerpt from autobiography'
    },
    {
        'author': "Liam O'Flaherty",
        'title': 'Two Stories about Flying: I. His First Flight',
        'author_born': '1896',
        'author_died': '1984',
        'origin': 'translated:english',
        'genre': 'short-story',
        'subject_era': 'none/nature?',
        'exam_status': 'mandatory',
        'memorize': 'no',
        'grade': '10',
        'source': 'https://cbseacademic.nic.in/web_material/CurriculumMain25/Sec/English_LL_2024-25.pdf',
        'doc_year': '2024',
        'retrieved': '2026-08-10',
        'note': 'First Flight Prose Ch 3 Part I; Irish author'
    },
    {
        'author': 'Frederick Forsyth',
        'title': 'Two Stories about Flying: II. Black Aeroplane',
        'author_born': '1938',
        'author_died': 'living',
        'origin': 'translated:english',
        'genre': 'short-story',
        'subject_era': 'WWII-aviation?',
        'exam_status': 'mandatory',
        'memorize': 'no',
        'grade': '10',
        'source': 'https://cbseacademic.nic.in/web_material/CurriculumMain25/Sec/English_LL_2024-25.pdf',
        'doc_year': '2024',
        'retrieved': '2026-08-10',
        'note': 'First Flight Prose Ch 3 Part II; British author'
    },
    {
        'author': 'Anne Frank',
        'title': 'From the Diary of Anne Frank',
        'author_born': '1929',
        'author_died': '1945',
        'origin': 'translated:dutch',
        'genre': 'essay',
        'subject_era': 'WWII-holocaust/nazi-occupation',
        'exam_status': 'mandatory',
        'memorize': 'no',
        'grade': '10',
        'source': 'https://cbseacademic.nic.in/web_material/CurriculumMain25/Sec/English_LL_2024-25.pdf',
        'doc_year': '2024',
        'retrieved': '2026-08-10',
        'note': 'First Flight Prose Ch 4; excerpt from Het Achterhuis translated from Dutch'
    },
    {
        'author': 'Lucio Rodrigues',
        'title': 'Glimpses of India: I. A Baker from Goa',
        'author_born': '1916',
        'author_died': '1973',
        'origin': 'domestic',
        'genre': 'essay',
        'subject_era': 'portuguese-goa-heritage?',
        'exam_status': 'mandatory',
        'memorize': 'no',
        'grade': '10',
        'source': 'https://cbseacademic.nic.in/web_material/CurriculumMain25/Sec/English_LL_2024-25.pdf',
        'doc_year': '2024',
        'retrieved': '2026-08-10',
        'note': 'First Flight Prose Ch 5 Part I; Indian Goan author'
    },
    {
        'author': 'Lokesh Abrol',
        'title': 'Glimpses of India: II. Coorg',
        'author_born': '~1950',
        'author_died': 'living',
        'origin': 'domestic',
        'genre': 'essay',
        'subject_era': 'coorg-martial-heritage?',
        'exam_status': 'mandatory',
        'memorize': 'no',
        'grade': '10',
        'source': 'https://cbseacademic.nic.in/web_material/CurriculumMain25/Sec/English_LL_2024-25.pdf',
        'doc_year': '2024',
        'retrieved': '2026-08-10',
        'note': 'First Flight Prose Ch 5 Part II; Indian author'
    },
    {
        'author': 'Arup Kumar Dutta',
        'title': 'Glimpses of India: III. Tea from Assam',
        'author_born': '1946',
        'author_died': 'living',
        'origin': 'domestic',
        'genre': 'short-story',
        'subject_era': 'assam-tea-culture?',
        'exam_status': 'mandatory',
        'memorize': 'no',
        'grade': '10',
        'source': 'https://cbseacademic.nic.in/web_material/CurriculumMain25/Sec/English_LL_2024-25.pdf',
        'doc_year': '2024',
        'retrieved': '2026-08-10',
        'note': 'First Flight Prose Ch 5 Part III; Assamese Indian author'
    },
    {
        'author': 'Gavin Maxwell',
        'title': 'Mijbil the Otter',
        'author_born': '1914',
        'author_died': '1969',
        'origin': 'translated:english',
        'genre': 'short-story',
        'subject_era': 'post-WWII-iraq-scotland?',
        'exam_status': 'mandatory',
        'memorize': 'no',
        'grade': '10',
        'source': 'https://cbseacademic.nic.in/web_material/CurriculumMain25/Sec/English_LL_2024-25.pdf',
        'doc_year': '2024',
        'retrieved': '2026-08-10',
        'note': 'First Flight Prose Ch 6; Scottish author, excerpt from Ring of Bright Water'
    },
    {
        'author': 'Vallikkannan (R. S. Krishnasamy)',
        'title': 'Madam Rides the Bus',
        'author_born': '1920',
        'author_died': '2006',
        'origin': 'domestic',
        'genre': 'short-story',
        'subject_era': 'modern-tamil-nadu-rural-life?',
        'exam_status': 'mandatory',
        'memorize': 'no',
        'grade': '10',
        'source': 'https://cbseacademic.nic.in/web_material/CurriculumMain25/Sec/English_LL_2024-25.pdf',
        'doc_year': '2024',
        'retrieved': '2026-08-10',
        'note': 'First Flight Prose Ch 7; translated from Tamil (Bussil Oru Payanam) by K. S. Sundaram'
    },
    {
        'author': 'Anonymous (Gautama Buddha / Betty Renshaw)',
        'title': 'The Sermon at Benares',
        'author_born': '~563 BCE',
        'author_died': '~483 BCE',
        'origin': 'domestic',
        'genre': 'essay',
        'subject_era': 'antiquity-ancient-india-buddhism',
        'exam_status': 'mandatory',
        'memorize': 'no',
        'grade': '10',
        'source': 'https://cbseacademic.nic.in/web_material/CurriculumMain25/Sec/English_LL_2024-25.pdf',
        'doc_year': '2024',
        'retrieved': '2026-08-10',
        'note': "First Flight Prose Ch 8; retelling of Kisa Gotami & Buddha's sermon"
    },
    {
        'author': 'Anton Chekhov',
        'title': 'The Proposal',
        'author_born': '1860',
        'author_died': '1904',
        'origin': 'translated:russian',
        'genre': 'play',
        'subject_era': '19th-c-russian-gentry-satire',
        'exam_status': 'mandatory',
        'memorize': 'no',
        'grade': '10',
        'source': 'https://cbseacademic.nic.in/web_material/CurriculumMain25/Sec/English_LL_2024-25.pdf',
        'doc_year': '2024',
        'retrieved': '2026-08-10',
        'note': 'First Flight Prose Ch 9; Russian play (Предложение) translated into English'
    },
    # --- FIRST FLIGHT (POETRY) ---
    {
        'author': 'Robert Frost',
        'title': 'Dust of Snow',
        'author_born': '1874',
        'author_died': '1963',
        'origin': 'translated:english',
        'genre': 'poem',
        'subject_era': 'none/nature',
        'exam_status': 'mandatory',
        'memorize': 'no',
        'grade': '10',
        'source': 'https://cbseacademic.nic.in/web_material/CurriculumMain25/Sec/English_LL_2024-25.pdf',
        'doc_year': '2024',
        'retrieved': '2026-08-10',
        'note': 'First Flight Poem 1; American poet'
    },
    {
        'author': 'Robert Frost',
        'title': 'Fire and Ice',
        'author_born': '1874',
        'author_died': '1963',
        'origin': 'translated:english',
        'genre': 'poem',
        'subject_era': '1920s-apocalyptic-apathy?',
        'exam_status': 'mandatory',
        'memorize': 'no',
        'grade': '10',
        'source': 'https://cbseacademic.nic.in/web_material/CurriculumMain25/Sec/English_LL_2024-25.pdf',
        'doc_year': '2024',
        'retrieved': '2026-08-10',
        'note': 'First Flight Poem 2; American poet'
    },
    {
        'author': 'Leslie Norris',
        'title': 'A Tiger in the Zoo',
        'author_born': '1921',
        'author_died': '2006',
        'origin': 'translated:english',
        'genre': 'poem',
        'subject_era': 'none/nature',
        'exam_status': 'mandatory',
        'memorize': 'no',
        'grade': '10',
        'source': 'https://cbseacademic.nic.in/web_material/CurriculumMain25/Sec/English_LL_2024-25.pdf',
        'doc_year': '2024',
        'retrieved': '2026-08-10',
        'note': 'First Flight Poem 3; Welsh poet'
    },
    {
        'author': 'Carolyn Wells',
        'title': 'How to Tell Wild Animals',
        'author_born': '1862',
        'author_died': '1942',
        'origin': 'translated:english',
        'genre': 'poem',
        'subject_era': 'none/humor',
        'exam_status': 'mandatory',
        'memorize': 'no',
        'grade': '10',
        'source': 'https://cbseacademic.nic.in/web_material/CurriculumMain25/Sec/English_LL_2024-25.pdf',
        'doc_year': '2024',
        'retrieved': '2026-08-10',
        'note': 'First Flight Poem 4; American poet'
    },
    {
        'author': 'John Berryman',
        'title': 'The Ball Poem',
        'author_born': '1914',
        'author_died': '1972',
        'origin': 'translated:english',
        'genre': 'poem',
        'subject_era': 'none/existential-loss?',
        'exam_status': 'mandatory',
        'memorize': 'no',
        'grade': '10',
        'source': 'https://cbseacademic.nic.in/web_material/CurriculumMain25/Sec/English_LL_2024-25.pdf',
        'doc_year': '2024',
        'retrieved': '2026-08-10',
        'note': 'First Flight Poem 5; American poet'
    },
    {
        'author': 'Robin Klein',
        'title': 'Amanda!',
        'author_born': '1936',
        'author_died': 'living',
        'origin': 'translated:english',
        'genre': 'poem',
        'subject_era': 'contemporary-adolescence?',
        'exam_status': 'mandatory',
        'memorize': 'no',
        'grade': '10',
        'source': 'https://cbseacademic.nic.in/web_material/CurriculumMain25/Sec/English_LL_2024-25.pdf',
        'doc_year': '2024',
        'retrieved': '2026-08-10',
        'note': 'First Flight Poem 6; Australian poet'
    },
    {
        'author': 'Adrienne Rich',
        'title': 'The Trees',
        'author_born': '1929',
        'author_died': '2012',
        'origin': 'translated:english',
        'genre': 'poem',
        'subject_era': '1960s-feminism-ecocriticism?',
        'exam_status': 'mandatory',
        'memorize': 'no',
        'grade': '10',
        'source': 'https://cbseacademic.nic.in/web_material/CurriculumMain25/Sec/English_LL_2024-25.pdf',
        'doc_year': '2024',
        'retrieved': '2026-08-10',
        'note': 'First Flight Poem 7; American poet'
    },
    {
        'author': 'Carl Sandburg',
        'title': 'Fog',
        'author_born': '1878',
        'author_died': '1967',
        'origin': 'translated:english',
        'genre': 'poem',
        'subject_era': 'none/nature',
        'exam_status': 'mandatory',
        'memorize': 'no',
        'grade': '10',
        'source': 'https://cbseacademic.nic.in/web_material/CurriculumMain25/Sec/English_LL_2024-25.pdf',
        'doc_year': '2024',
        'retrieved': '2026-08-10',
        'note': 'First Flight Poem 8; American poet'
    },
    {
        'author': 'Ogden Nash',
        'title': 'The Tale of Custard the Dragon',
        'author_born': '1902',
        'author_died': '1971',
        'origin': 'translated:english',
        'genre': 'poem',
        'subject_era': 'none/humor',
        'exam_status': 'mandatory',
        'memorize': 'no',
        'grade': '10',
        'source': 'https://cbseacademic.nic.in/web_material/CurriculumMain25/Sec/English_LL_2024-25.pdf',
        'doc_year': '2024',
        'retrieved': '2026-08-10',
        'note': 'First Flight Poem 9; American poet'
    },
    {
        'author': 'William Butler Yeats',
        'title': 'For Anne Gregory',
        'author_born': '1865',
        'author_died': '1939',
        'origin': 'translated:english',
        'genre': 'poem',
        'subject_era': 'none/romance',
        'exam_status': 'mandatory',
        'memorize': 'no',
        'grade': '10',
        'source': 'https://cbseacademic.nic.in/web_material/CurriculumMain25/Sec/English_LL_2024-25.pdf',
        'doc_year': '2024',
        'retrieved': '2026-08-10',
        'note': 'First Flight Poem 10; Irish poet'
    },
    # --- FOOTPRINTS WITHOUT FEET ---
    {
        'author': 'James Herriot',
        'title': 'A Triumph of Surgery',
        'author_born': '1916',
        'author_died': '1995',
        'origin': 'translated:english',
        'genre': 'short-story',
        'subject_era': 'mid-20th-c-yorkshire-veterinary?',
        'exam_status': 'mandatory',
        'memorize': 'no',
        'grade': '10',
        'source': 'https://cbseacademic.nic.in/web_material/CurriculumMain25/Sec/English_LL_2024-25.pdf',
        'doc_year': '2024',
        'retrieved': '2026-08-10',
        'note': 'Footprints Without Feet Ch 1; British author'
    },
    {
        'author': 'Ruskin Bond',
        'title': "The Thief's Story",
        'author_born': '1934',
        'author_died': 'living',
        'origin': 'domestic',
        'genre': 'short-story',
        'subject_era': 'modern-indian-small-town-morality?',
        'exam_status': 'mandatory',
        'memorize': 'no',
        'grade': '10',
        'source': 'https://cbseacademic.nic.in/web_material/CurriculumMain25/Sec/English_LL_2024-25.pdf',
        'doc_year': '2024',
        'retrieved': '2026-08-10',
        'note': 'Footprints Without Feet Ch 2; Indian English author'
    },
    {
        'author': 'Robert Arthur',
        'title': 'The Midnight Visitor',
        'author_born': '1909',
        'author_died': '1969',
        'origin': 'translated:english',
        'genre': 'short-story',
        'subject_era': 'cold-war-espionage?',
        'exam_status': 'mandatory',
        'memorize': 'no',
        'grade': '10',
        'source': 'https://cbseacademic.nic.in/web_material/CurriculumMain25/Sec/English_LL_2024-25.pdf',
        'doc_year': '2024',
        'retrieved': '2026-08-10',
        'note': 'Footprints Without Feet Ch 3; American author'
    },
    {
        'author': 'Victor Canning',
        'title': 'A Question of Trust',
        'author_born': '1911',
        'author_died': '1986',
        'origin': 'translated:english',
        'genre': 'short-story',
        'subject_era': 'mid-20th-c-crime/irony?',
        'exam_status': 'mandatory',
        'memorize': 'no',
        'grade': '10',
        'source': 'https://cbseacademic.nic.in/web_material/CurriculumMain25/Sec/English_LL_2024-25.pdf',
        'doc_year': '2024',
        'retrieved': '2026-08-10',
        'note': 'Footprints Without Feet Ch 4; British author'
    },
    {
        'author': 'H.G. Wells',
        'title': 'Footprints Without Feet',
        'author_born': '1866',
        'author_died': '1946',
        'origin': 'translated:english',
        'genre': 'novella',
        'subject_era': 'victorian-science-morality',
        'exam_status': 'mandatory',
        'memorize': 'no',
        'grade': '10',
        'source': 'https://cbseacademic.nic.in/web_material/CurriculumMain25/Sec/English_LL_2024-25.pdf',
        'doc_year': '2024',
        'retrieved': '2026-08-10',
        'note': 'Footprints Without Feet Ch 5; excerpt from The Invisible Man; British author'
    },
    {
        'author': 'Robert W. Peterson',
        'title': 'The Making of a Scientist',
        'author_born': '1925',
        'author_died': '2006',
        'origin': 'translated:english',
        'genre': 'essay',
        'subject_era': '20th-c-american-science/biography',
        'exam_status': 'mandatory',
        'memorize': 'no',
        'grade': '10',
        'source': 'https://cbseacademic.nic.in/web_material/CurriculumMain25/Sec/English_LL_2024-25.pdf',
        'doc_year': '2024',
        'retrieved': '2026-08-10',
        'note': 'Footprints Without Feet Ch 6; biography of Richard Ebright; American author'
    },
    {
        'author': 'Guy de Maupassant',
        'title': 'The Necklace',
        'author_born': '1850',
        'author_died': '1893',
        'origin': 'translated:french',
        'genre': 'short-story',
        'subject_era': '19th-c-paris-bourgeoisie',
        'exam_status': 'mandatory',
        'memorize': 'no',
        'grade': '10',
        'source': 'https://cbseacademic.nic.in/web_material/CurriculumMain25/Sec/English_LL_2024-25.pdf',
        'doc_year': '2024',
        'retrieved': '2026-08-10',
        'note': 'Footprints Without Feet Ch 7; French story (La Parure) translated into English'
    },
    {
        'author': 'K.A. Abbas (Khwaja Ahmad Abbas)',
        'title': 'Bholi',
        'author_born': '1914',
        'author_died': '1987',
        'origin': 'domestic',
        'genre': 'short-story',
        'subject_era': '20th-c-indian-rural-female-education',
        'exam_status': 'mandatory',
        'memorize': 'no',
        'grade': '10',
        'source': 'https://cbseacademic.nic.in/web_material/CurriculumMain25/Sec/English_LL_2024-25.pdf',
        'doc_year': '2024',
        'retrieved': '2026-08-10',
        'note': 'Footprints Without Feet Ch 8; Indian author'
    },
    {
        'author': 'Claire Boiko',
        'title': 'The Book that Saved the Earth',
        'author_born': '1923',
        'author_died': '2018',
        'origin': 'translated:english',
        'genre': 'play',
        'subject_era': '25th-c-sci-fi/nursery-rhymes?',
        'exam_status': 'mandatory',
        'memorize': 'no',
        'grade': '10',
        'source': 'https://cbseacademic.nic.in/web_material/CurriculumMain25/Sec/English_LL_2024-25.pdf',
        'doc_year': '2024',
        'retrieved': '2026-08-10',
        'note': 'Footprints Without Feet Ch 9; American author'
    },
    # --- HINDI COURSE A (KSHITIJ PART 2 & KRITIKA PART 2) ---
    {
        'author': 'सूरदास (Surdas)',
        'title': 'पद ("Pad" - Verses)',
        'author_born': '1478',
        'author_died': '1583',
        'origin': 'domestic',
        'genre': 'poem-cycle',
        'subject_era': 'bhakti-era-gopi-krishna-devotion',
        'exam_status': 'mandatory',
        'memorize': 'no',
        'grade': '10',
        'source': 'https://cbseacademic.nic.in/web_material/CurriculumMain25/Sec/Hindi_A_Sec_2024-25.pdf',
        'doc_year': '2024',
        'retrieved': '2026-08-10',
        'note': 'Kshitij Part-2 Kavya Ch 1; Bhakti movement poetry in Braj Bhasha'
    },
    {
        'author': 'तुलसीदास (Tulsidas)',
        'title': 'राम-लक्ष्मण-परशुराम संवाद ("Ram-Lakshman-Parashuram Samvad" - Dialogue between Ram, Lakshman and Parashuram)',
        'author_born': '1532',
        'author_died': '1623',
        'origin': 'domestic',
        'genre': 'poem',
        'subject_era': 'antiquity-ramayana-epic',
        'exam_status': 'mandatory',
        'memorize': 'no',
        'grade': '10',
        'source': 'https://cbseacademic.nic.in/web_material/CurriculumMain25/Sec/Hindi_A_Sec_2024-25.pdf',
        'doc_year': '2024',
        'retrieved': '2026-08-10',
        'note': 'Kshitij Part-2 Kavya Ch 2; excerpt from Ramcharitmanas'
    },
    {
        'author': 'जयशंकर प्रसाद (Jaishankar Prasad)',
        'title': 'आत्मकथ्य ("Atmakathya" - Personal Statement / Autobiography in Verse)',
        'author_born': '1889',
        'author_died': '1937',
        'origin': 'domestic',
        'genre': 'poem',
        'subject_era': 'chhayavad-era-introspection?',
        'exam_status': 'mandatory',
        'memorize': 'no',
        'grade': '10',
        'source': 'https://cbseacademic.nic.in/web_material/CurriculumMain25/Sec/Hindi_A_Sec_2024-25.pdf',
        'doc_year': '2024',
        'retrieved': '2026-08-10',
        'note': 'Kshitij Part-2 Kavya Ch 4; Chhayavadi poetry'
    },
    {
        'author': 'सूर्यकांत त्रिपाठी \'निराला\' (Suryakant Tripathi \'Nirala\')',
        'title': 'उत्साह और अट नहीं रही ("Utsah" aur "Att Nahi Rahi" - Enthusiasm / Uncontainable Spring)',
        'author_born': '1899',
        'author_died': '1961',
        'origin': 'domestic',
        'genre': 'poem-cycle',
        'subject_era': 'chhayavad-era-nature-revolution?',
        'exam_status': 'mandatory',
        'memorize': 'no',
        'grade': '10',
        'source': 'https://cbseacademic.nic.in/web_material/CurriculumMain25/Sec/Hindi_A_Sec_2024-25.pdf',
        'doc_year': '2024',
        'retrieved': '2026-08-10',
        'note': 'Kshitij Part-2 Kavya Ch 5; two Chhayavadi poems'
    },
    {
        'author': 'नागार्जुन (Nagarjun)',
        'title': 'यह दंतुरित मुस्कान और फसल ("Yah Danturit Muskan" aur "Fasal" - This Baby Smile and Harvest)',
        'author_born': '1911',
        'author_died': '1998',
        'origin': 'domestic',
        'genre': 'poem-cycle',
        'subject_era': 'pragativad-era-rural-life?',
        'exam_status': 'mandatory',
        'memorize': 'no',
        'grade': '10',
        'source': 'https://cbseacademic.nic.in/web_material/CurriculumMain25/Sec/Hindi_A_Sec_2024-25.pdf',
        'doc_year': '2024',
        'retrieved': '2026-08-10',
        'note': 'Kshitij Part-2 Kavya Ch 6; Progressive poetry'
    },
    {
        'author': 'मंगलेश डबराल (Manglesh Dabral)',
        'title': 'संगतकार ("Sangatkar" - The Accompanist)',
        'author_born': '1948',
        'author_died': '2020',
        'origin': 'domestic',
        'genre': 'poem',
        'subject_era': 'contemporary-artistic-labor?',
        'exam_status': 'mandatory',
        'memorize': 'no',
        'grade': '10',
        'source': 'https://cbseacademic.nic.in/web_material/CurriculumMain25/Sec/Hindi_A_Sec_2024-25.pdf',
        'doc_year': '2024',
        'retrieved': '2026-08-10',
        'note': 'Kshitij Part-2 Kavya Ch 9; poem on background artists'
    },
    {
        'author': 'स्वयं प्रकाश (Swayam Prakash)',
        'title': 'नेताजी का चश्मा ("Netaji Ka Chashma" - Netaji\'s Spectacles)',
        'author_born': '1947',
        'author_died': '2019',
        'origin': 'domestic',
        'genre': 'short-story',
        'subject_era': 'post-independence-patriotism/bose-legacy?',
        'exam_status': 'mandatory',
        'memorize': 'no',
        'grade': '10',
        'source': 'https://cbseacademic.nic.in/web_material/CurriculumMain25/Sec/Hindi_A_Sec_2024-25.pdf',
        'doc_year': '2024',
        'retrieved': '2026-08-10',
        'note': 'Kshitij Part-2 Gadya Ch 10; story on Subhas Chandra Bose statue'
    },
    {
        'author': 'रामवृक्ष बेनीपुरी (Ramvriksha Benipuri)',
        'title': 'बालगोबिन भगत ("Baalgobind Bhagat")',
        'author_born': '1899',
        'author_died': '1968',
        'origin': 'domestic',
        'genre': 'short-story',
        'subject_era': '20th-c-bihar-rural-saintliness?',
        'exam_status': 'mandatory',
        'memorize': 'no',
        'grade': '10',
        'source': 'https://cbseacademic.nic.in/web_material/CurriculumMain25/Sec/Hindi_A_Sec_2024-25.pdf',
        'doc_year': '2024',
        'retrieved': '2026-08-10',
        'note': 'Kshitij Part-2 Gadya Ch 11; character sketch'
    },
    {
        'author': 'यशपाल (Yashpal)',
        'title': 'लखनवी अंदाज़ ("Lakhnavi Andaz" - Lucknow Style)',
        'author_born': '1903',
        'author_died': '1976',
        'origin': 'domestic',
        'genre': 'short-story',
        'subject_era': 'post-feudal-gentry-pretension?',
        'exam_status': 'mandatory',
        'memorize': 'no',
        'grade': '10',
        'source': 'https://cbseacademic.nic.in/web_material/CurriculumMain25/Sec/Hindi_A_Sec_2024-25.pdf',
        'doc_year': '2024',
        'retrieved': '2026-08-10',
        'note': 'Kshitij Part-2 Gadya Ch 12; satirical story on decaying feudal aristocracy'
    },
    {
        'author': 'मन्नू भंडारी (Mannu Bhandari)',
        'title': 'एक कहानी यह भी ("Ek Kahani Yeh Bhi" - This Too Is a Story)',
        'author_born': '1931',
        'author_died': '2021',
        'origin': 'domestic',
        'genre': 'essay',
        'subject_era': '1942-quit-india-movement/female-autonomy?',
        'exam_status': 'mandatory',
        'memorize': 'no',
        'grade': '10',
        'source': 'https://cbseacademic.nic.in/web_material/CurriculumMain25/Sec/Hindi_A_Sec_2024-25.pdf',
        'doc_year': '2024',
        'retrieved': '2026-08-10',
        'note': 'Kshitij Part-2 Gadya Ch 14; autobiographical essay touching 1947 independence'
    },
    {
        'author': 'यतींद्र मिश्र (Yatindra Mishra)',
        'title': 'नौबतखाने में इबादत ("Naubatkhane Mein Ibadat" - Worship in the Music Chamber)',
        'author_born': '1977',
        'author_died': 'living',
        'origin': 'domestic',
        'genre': 'essay',
        'subject_era': 'post-independence-benares-shehnai-bismillah-khan?',
        'exam_status': 'mandatory',
        'memorize': 'no',
        'grade': '10',
        'source': 'https://cbseacademic.nic.in/web_material/CurriculumMain25/Sec/Hindi_A_Sec_2024-25.pdf',
        'doc_year': '2024',
        'retrieved': '2026-08-10',
        'note': 'Kshitij Part-2 Gadya Ch 16; portrait of Ustad Bismillah Khan'
    },
    {
        'author': 'भदंत आनंद कौसल्यायन (Bhadant Anand Kausalyayan)',
        'title': 'संस्कृति ("Sanskriti" - Culture)',
        'author_born': '1905',
        'author_died': '1988',
        'origin': 'domestic',
        'genre': 'essay',
        'subject_era': '20th-c-buddhist-humanism?',
        'exam_status': 'mandatory',
        'memorize': 'no',
        'grade': '10',
        'source': 'https://cbseacademic.nic.in/web_material/CurriculumMain25/Sec/Hindi_A_Sec_2024-25.pdf',
        'doc_year': '2024',
        'retrieved': '2026-08-10',
        'note': 'Kshitij Part-2 Gadya Ch 17; philosophical essay'
    },
    {
        'author': 'शिवपूजन सहाय (Shivpujan Sahay)',
        'title': 'माता का आँचल ("Mata Ka Aanchal" - Mother\'s Lap)',
        'author_born': '1893',
        'author_died': '1963',
        'origin': 'domestic',
        'genre': 'novella',
        'subject_era': '1920s-rural-bihar-childhood?',
        'exam_status': 'mandatory',
        'memorize': 'no',
        'grade': '10',
        'source': 'https://cbseacademic.nic.in/web_material/CurriculumMain25/Sec/Hindi_A_Sec_2024-25.pdf',
        'doc_year': '2024',
        'retrieved': '2026-08-10',
        'note': 'Kritika Part-2 Ch 1; excerpt from Dehati Duniya (1926)'
    },
    {
        'author': 'कमलेश्वर (Kamleshwar)',
        'title': 'साना-साना हाथ जोड़ि ("Sana-Sana Hath Jodi" - Joining Hands in Prayer)',
        'author_born': '1932',
        'author_died': '2007',
        'origin': 'domestic',
        'genre': 'essay',
        'subject_era': 'contemporary-sikkim-border-labor?',
        'exam_status': 'mandatory',
        'memorize': 'no',
        'grade': '10',
        'source': 'https://cbseacademic.nic.in/web_material/CurriculumMain25/Sec/Hindi_A_Sec_2024-25.pdf',
        'doc_year': '2024',
        'retrieved': '2026-08-10',
        'note': 'Kritika Part-2 Ch 3; travelogue on Sikkim and road workers'
    },
    {
        'author': 'अज्ञेय (S.H. Vatsyayan \'Agyeya\')',
        'title': 'मैं क्यों लिखता हूँ? ("Main Kyon Likhata Hoon?" - Why Do I Write?)',
        'author_born': '1911',
        'author_died': '1987',
        'origin': 'domestic',
        'genre': 'essay',
        'subject_era': 'hiroshima-atomic-bomb',
        'exam_status': 'mandatory',
        'memorize': 'no',
        'grade': '10',
        'source': 'https://cbseacademic.nic.in/web_material/CurriculumMain25/Sec/Hindi_A_Sec_2024-25.pdf',
        'doc_year': '2024',
        'retrieved': '2026-08-10',
        'note': 'Kritika Part-2 Ch 5; essay on visiting Hiroshima bomb site'
    }
]

file_path = '/home/diablo/book10/corpus/in-2025.tsv'

with open(file_path, 'w', encoding='utf-8', newline='') as f:
    writer = csv.DictWriter(f, fieldnames=headers, delimiter='\t')
    writer.writeheader()
    for r in rows:
        writer.writerow(r)

print(f'Successfully written {len(rows)} rows to {file_path}')
