#!/bin/bash
# Essay wave 1 (sol's order after UA): RU, VN, KZ, CN, BO — then recon the rest.
cd /home/diablo/book10 || exit 1
./tools/essay.sh ru ru-2025 "The adjacent essay to Ukraine's (drafts/ua.md — read it for contrast, don't repeat it): Russia's window at OGE level is ONE omnibus choice row — 'works of foreign literature, by choice (including Homer, Cervantes, Shakespeare, Molière et al.)' — beside 47 domestic rows reaching back to the 12th century. The essay's spine is that door: a whole world compressed to a parenthesis, in the codifier of a country whose 19th-century canon the rest of the corpus still imports. Career it on what the codifier IS (FIPI, the exam's legal text), the ancestor-cult shape of the domestic list as CONTEXT for the window's size (not as a ranking), and close on the parenthesis itself. The 2023 codifier realignment may be gestured only with its news receipt from notes/scout-canon.md and marked as outside the corpus."
./tools/essay.sh vn vn-2024 "Vietnam's door is a QUOTA: the program requires choice from named foreign literary traditions (the table and documents show which — verify the exact rule and quote it), with 29 choice-list foreign rows in a 108-row anthology table spanning grades (honor the grade-span caveat from confirm/recon). Russian literature is a named required tradition; Aitmatov and Chekhov appear. The errand candidates are rich; close-read one. Mind the 33 era corrections applied in recon."
./tools/essay.sh kz kz-2023 "Kazakhstan: the richest imperial-language shelf in the reliable files — 21 of 27 foreign rows translated from Russian, plus Kyrgyz and English. Both mandatory and choice shelves visible in a bilingual (Kazakh/Russian-language schools) system. Write the Russian shelf as plain fact with the care AGENT.md demands: admission, never why — the file cannot distinguish inheritance, language policy, esteem, or convenience, and the essay says so. Memorization codings were reconciled; only cite what survived."
./tools/essay.sh cn cn-2024 "China: the narrowest listed window in the corpus — and after reconciliation it is FOUR receipted foreign mandates, not five: Verne, Snow, Ostrovsky, Brontë; Fabre is quarantined pending a work-level receipt (say so in Limits — the quarantine is itself good method on display). Each of the four runs a visible errand; the jewel is Edgar Snow — the American whose book about the Long March is China's chosen foreign reading about itself (and, cross-book, the West's main source on that march). Keep it compact (1,200-1,600 words): a small shelf deserves a small, perfect essay."
./tools/essay.sh bo bo-2024 "Bolivia: the anthology door — 25 foreign rows that are pages in a state textbook (texto de aprendizaje), not exam mandates; the essay must never harden anthology-presence into obligation. European classics, Russian novels and Latin American writing sit on one shelf; the door itself (a ministry that prints THE book rather than listing books) is the finding. All rows carried local support in the confirm pass."
echo "=== recon rest ==="
for t in by-2024 in-2025 jp-2024 mx-2024 br-2024 au-2024 us-2024 uk-aqa-2025 it-2025 de-2024 mn-2024; do
  ./tools/recon.sh "$t"
done
echo "ESSAY WAVE 1 DONE: $(ls drafts/*.md | wc -l) drafts, $(ls notes/recon-*.md | wc -l) recons"
